INSERT INTO country (id, name)
VALUES (1, 'Россия'),
       (2, 'Белоруссия'),
       (3, 'Армения'),
       (4, 'Грузия'),
       (5, 'Германия'),
       (6, 'Франция'),
       (7, 'Великобритания'),
       (8, 'Италия'),
       (9, 'Испания'),
       (10, 'Китай'),
       (11, 'США'),
       (12, 'Канада'),
       (13, 'Иран');

INSERT INTO territory_type (id, name)
VALUES (1, 'Страна'),
       (2, 'Область'),
       (3, 'Город'),
       (4, 'Село'),
       (5, 'Губерния'),
       (6, 'Графство'),
       (7, 'Штат');

INSERT INTO ruler (id, last_name, first_name, patronymic, nickname, birth_date, death_date, century)
VALUES (1, 'Путин', 'Владимир', 'Владимирович', NULL, '1952-10-07', NULL, 21),
       (2, 'Сталин', 'Иосиф', 'Виссарионович', NULL, '1878-12-18', '1953-03-05', 20),
       (3, 'Романов', 'Пётр', 'Алексеевич', 'Пётр Великий', '1672-06-09', '1725-02-08', 18),
       (4, 'Рюрикович', 'Иван', 'Васильевич', 'Иван Грозный', '1530-08-25', '1584-03-28', 16),
       (5, 'Гусев', 'Александр', 'Викторович', NULL, '1963-07-27', NULL, 21),
       (6, 'Кстенин', 'Вадим', 'Юрьевич', NULL, '1975-06-12', NULL, 21),
       (7, 'Апраксин', 'Фёдор', 'Матвеевич', NULL, '1661-12-07', '1728-04-21', 18),
       (8, 'Усов', 'Сергей', 'Иванович', NULL, NULL, NULL, 21),
       (9, 'Собянин', 'Сергей', 'Семёнович', NULL, NULL, NULL, 21),
       (10, 'Лужков', 'Юрий', 'Михайлович', NULL, NULL, NULL, 21),
       (11, 'Байден', 'Джозеф', 'Робинетт', NULL, NULL, NULL, 21),
       (12, 'Уитмер', 'Грехкен', NULL, NULL, NULL, NULL, 21);

INSERT INTO territorial_unit (id, name, territory_type_id, foundation_date, country_id, population)
VALUES (1, 'Россия', (SELECT id FROM territory_type WHERE name LIKE 'Страна'), '862-01-01',
        (SELECT id FROM country WHERE name LIKE 'Россия'), 146980061),
       (2, 'Воронежская область', (SELECT id FROM territory_type WHERE name LIKE 'Область'), '1943-06-13',
        (SELECT id FROM country WHERE name LIKE 'Россия'), 2285282),
       (3, 'Воронеж', (SELECT id FROM territory_type WHERE name LIKE 'Город'), '1586-01-01',
        (SELECT id FROM country WHERE name LIKE 'Россия'), 1051995),
       (4, 'Москва', (SELECT id FROM territory_type WHERE name LIKE 'Город'), '1147-01-01',
        (SELECT id FROM country WHERE name LIKE 'Россия'), 13104177),
       (5, 'Каширское', (SELECT id FROM territory_type WHERE name LIKE 'Село'), '1764-01-01',
        (SELECT id FROM country WHERE name LIKE 'Россия'), 4166),
       (6, 'США', (SELECT id FROM territory_type WHERE name LIKE 'Страна'), '1776-07-04',
        (SELECT id FROM country WHERE name LIKE 'США'), 315000000),
       (7, 'Нью-Йорк', (SELECT id FROM territory_type WHERE name LIKE 'Город'), '1624-01-01',
        (SELECT id FROM country WHERE name LIKE 'США'), 8467513),
       (8, 'Мичиган', (SELECT id FROM territory_type WHERE name LIKE 'Штат'), '1837-01-26',
        (SELECT id FROM country WHERE name LIKE 'США'), 10077331),
       (9, 'Минск', (SELECT id FROM territory_type WHERE name LIKE 'Город'), '1800-01-01',
        (SELECT id FROM country WHERE name LIKE 'Белоруссия'), 2051995);

INSERT INTO site (id, address, territorial_unit_id)
VALUES (1, 'https://www.mos.ru', (SELECT id FROM territorial_unit WHERE name LIKE 'Москва')),
       (2, 'https://um.mos.ru/excursions', (SELECT id FROM territorial_unit WHERE name LIKE 'Москва')),
       (3, 'https://www.nyc.gov', (SELECT id FROM territorial_unit WHERE name LIKE 'Нью-Йорк')),
       (4, 'https://www.nyhistory.org', (SELECT id FROM territorial_unit WHERE name LIKE 'Нью-Йорк')),
       (5, 'https://voronezh-city.ru', (SELECT id FROM territorial_unit WHERE name LIKE 'Воронеж')),
       (6, 'https://culture.govvrn.ru', (SELECT id FROM territorial_unit WHERE name LIKE 'Воронеж')),
       (7, 'https://www.govvrn.ru', (SELECT id FROM territorial_unit WHERE name LIKE 'Воронежская область')),
       (8, 'https://culture.govvrn.ru', (SELECT id FROM territorial_unit WHERE name LIKE 'Воронежская область')),
       (9, 'https://akmrvo.gosuslugi.ru/', (SELECT id FROM territorial_unit WHERE name LIKE 'Каширское'));

INSERT INTO ruler_territorial_unit (id, ruler_id, territorial_unit_id, start_date, end_date, century)
VALUES (1, (SELECT id FROM ruler WHERE last_name = 'Путин'), (SELECT id FROM territorial_unit WHERE name LIKE 'Россия'),
        '2000-01-01', '2004-01-01', 21),
       (2, (SELECT id FROM ruler WHERE last_name LIKE 'Путин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Россия'), '2012-01-01', '2018-01-01', 21),
       (3, (SELECT id FROM ruler WHERE last_name LIKE 'Сталин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Россия'), '1924-01-01', '1953-01-01', 20),
       (4, (SELECT id FROM ruler WHERE nickname LIKE 'Пётр Великий'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Россия'), '1682-01-01', '1725-01-01', 18),
       (5, (SELECT id FROM ruler WHERE nickname LIKE 'Иван Грозный'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Россия'), '1547-01-01', '1584-01-01', 16),
       (6, (SELECT id FROM ruler WHERE last_name LIKE 'Гусев'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Воронежская область'), '2018-01-01', '2023-01-01', 21),
       (7, (SELECT id FROM ruler WHERE last_name LIKE 'Апраксин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Воронеж'), '1700-01-01', '1728-01-01', 18),
       (8, (SELECT id FROM ruler WHERE last_name LIKE 'Кстенин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Воронеж'), '2018-01-01', NULL, 21),
       (9, (SELECT id FROM ruler WHERE last_name LIKE 'Усов'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Каширское'), '2018-01-01', NULL, 21),
       (10, (SELECT id FROM ruler WHERE last_name LIKE 'Собянин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Москва'), '2013-01-01', '2018-01-01', 21),
       (11, (SELECT id FROM ruler WHERE last_name LIKE 'Лужков'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Москва'), '1992-01-01', '2010-01-01', 21),
       (12, (SELECT id FROM ruler WHERE last_name LIKE 'Байден'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'США'), '2020-01-01', NULL, 21),
       (13, (SELECT id FROM ruler WHERE last_name LIKE 'Собянин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Минск'), '2018-01-01', '2020-01-01', 21),
       (14, (SELECT id FROM ruler WHERE last_name LIKE 'Усов'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Минск'), '2020-01-01', '2022-01-01', 21),
       (15, (SELECT id FROM ruler WHERE last_name LIKE 'Лужков'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Минск'), '2022-01-01', '2024-01-01', 21),
       (16, (SELECT id FROM ruler WHERE last_name LIKE 'Кстенин'),
        (SELECT id FROM territorial_unit WHERE name LIKE 'Минск'), '2024-01-01', '2026-01-01', 21);