eureka:
  instance:
    hostname: localhost

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

name:
  value: rntgroup

spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: health, prometheus

  metrics:
    export:
      prometheus:
        enabled: true

    distribution:
      percentiles-histogram:
        "[http.server.requests]": true