server:
  port: 8060

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  jpa:
    properties.hibernate:
      hbm2ddl.auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  config:
    employee-url: http://localhost:8222/api/v1/employees