server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: department-service
          uri: lb:http://DEPARTMENT-SERVICE
          predicates:
            - Path=/api/v1/departments/**

        - id: employee-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/employees/**

        - id: position-service
          uri: lb:http://EMPLOYEE-SERVICE
          predicates:
            - Path=/api/v1/positions/**